//Throw possibilita intencionalmente lan√ßar um erro no programa

#include <iostream>;

using namespace std;

/*
try {
  int num = 10;
  throw 505;
}
catch (int erro) {
  cout << "Error occurred: " << erro;
}
*/